### ISSUE TITLE
Do not build on JDK 11

### ISSUE THREAD

**Issue by cardil** [vavr-io/vavr-beanvalidation2#6]
I tried to build this library on JDK 11 and it didn't. I think that the reason is that surefire 2.12 is being used and it had failed to operate with jacoco on this version of JDK.

Build log can be seen here: https://travis-ci.org/vavr-io/vavr-beanvalidation2/jobs/566004871

I think that bumping version of surefire will fix that issue. 

To reproduce this issue `.travis.yml` file should be either:

```yml
language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
```
or: 
```yml
language: java
sudo: false
dist: xenial
jdk:
  - openjdk8
  - openjdk11
```

Of course, it is also possible to test on both vendors of JDK using Travis CI:

```yml
language: java
sudo: false
matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk11
      dist: trusty
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk11
      dist: xenial
```
